// api/github/commit.js
// Chrxmaticc Copilot — GitHub Commit API
// Creates commits via GitHub API with repo scope

module.exports = async function(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  if (req.method === 'OPTIONS') return res.status(200).end();
  if (req.method !== 'POST') return res.status(405).json({ error: 'POST only' });

  var body = req.body || {};
  var accessToken = body.token || '';
  var repo = body.repo || '';
  var files = body.files || [];
  var message = body.message || 'Generated by Chrxmaticc Copilot';
  var branch = body.branch || 'main';

  if (!accessToken || !repo || files.length === 0) {
    return res.status(400).json({ error: 'Missing token, repo, or files' });
  }

  try {
    // Get the latest commit SHA for the branch
    var branchRes = await fetch('https://api.github.com/repos/' + repo + '/git/ref/heads/' + branch, {
      headers: {
        'Authorization': 'Bearer ' + accessToken,
        'User-Agent': 'Chrxmaticc-Copilot',
        'Accept': 'application/json'
      }
    });

    if (!branchRes.ok) {
      var branchErr = await branchRes.json();
      return res.status(400).json({ error: 'Repo not found or no access: ' + (branchErr.message || 'unknown') });
    }

    var branchData = await branchRes.json();
    var parentSha = branchData.object.sha;

    // Get the base tree SHA from the parent commit
    var parentCommitRes = await fetch('https://api.github.com/repos/' + repo + '/git/commits/' + parentSha, {
      headers: {
        'Authorization': 'Bearer ' + accessToken,
        'User-Agent': 'Chrxmaticc-Copilot',
        'Accept': 'application/json'
      }
    });
    var parentCommitData = await parentCommitRes.json();
    var baseTreeSha = parentCommitData.tree.sha;

    // Create blobs for each file
    var treeItems = [];
    for (var f of files) {
      var blobRes = await fetch('https://api.github.com/repos/' + repo + '/git/blobs', {
        method: 'POST',
        headers: {
          'Authorization': 'Bearer ' + accessToken,
          'Content-Type': 'application/json',
          'User-Agent': 'Chrxmaticc-Copilot',
          'Accept': 'application/json'
        },
        body: JSON.stringify({
          content: f.content,
          encoding: 'utf-8'
        })
      });

      if (!blobRes.ok) {
        var blobErr = await blobRes.json();
        return res.status(400).json({ error: 'Failed to create blob for ' + f.path + ': ' + (blobErr.message || 'unknown') });
      }

      var blobData = await blobRes.json();
      treeItems.push({
        path: f.path,
        mode: '100644',
        type: 'blob',
        sha: blobData.sha
      });
    }

    // Create a new tree
    var newTreeRes = await fetch('https://api.github.com/repos/' + repo + '/git/trees', {
      method: 'POST',
      headers: {
        'Authorization': 'Bearer ' + accessToken,
        'Content-Type': 'application/json',
        'User-Agent': 'Chrxmaticc-Copilot',
        'Accept': 'application/json'
      },
      body: JSON.stringify({
        base_tree: baseTreeSha,
        tree: treeItems
      })
    });

    if (!newTreeRes.ok) {
      var treeErr = await newTreeRes.json();
      return res.status(400).json({ error: 'Failed to create tree: ' + (treeErr.message || 'unknown') });
    }

    var newTreeData = await newTreeRes.json();

    // Create commit
    var commitRes = await fetch('https://api.github.com/repos/' + repo + '/git/commits', {
      method: 'POST',
      headers: {
        'Authorization': 'Bearer ' + accessToken,
        'Content-Type': 'application/json',
        'User-Agent': 'Chrxmaticc-Copilot',
        'Accept': 'application/json'
      },
      body: JSON.stringify({
        message: message,
        tree: newTreeData.sha,
        parents: [parentSha]
      })
    });

    if (!commitRes.ok) {
      var commitErr = await commitRes.json();
      return res.status(400).json({ error: 'Failed to create commit: ' + (commitErr.message || 'unknown') });
    }

    var commitData = await commitRes.json();

    // Update branch reference
    var updateRefRes = await fetch('https://api.github.com/repos/' + repo + '/git/refs/heads/' + branch, {
      method: 'PATCH',
      headers: {
        'Authorization': 'Bearer ' + accessToken,
        'Content-Type': 'application/json',
        'User-Agent': 'Chrxmaticc-Copilot',
        'Accept': 'application/json'
      },
      body: JSON.stringify({
        sha: commitData.sha,
        force: false
      })
    });

    if (!updateRefRes.ok) {
      var refErr = await updateRefRes.json();
      return res.status(400).json({ error: 'Failed to update branch: ' + (refErr.message || 'unknown') });
    }

    res.status(200).json({
      success: true,
      commit: commitData.sha,
      url: 'https://github.com/' + repo + '/commit/' + commitData.sha
    });

  } catch(e) {
    res.status(500).json({ error: 'GitHub API error: ' + e.message });
  }
};
